[package]
name = "yewdux"
version = "0.6.1"
authors = ["Noah <noah@coronasoftware.net>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/yewdux/yewdux"
readme = "README.md"
description = "Ergonomic state management for Yew applications"
keywords = ["yew", "state", "redux", "shared", "container"]
categories = ["wasm", "web-programming", "rust-patterns"]


[dependencies]
yewdux-macros = { path = "../yewdux-macros" }
serde = { version = "1.0.114", features = ["rc"] }
serde_json = "1.0.64"
web-sys = "0.3.51"
yew = { git = "https://github.com/yewstack/yew.git" }
anymap = "0.12.1"
slab = "0.4"
thiserror = "1.0"
wasm-bindgen = "0.2"

