[package]
name = "yewdux-input"
version = "0.1.0"
edition = "2018"

[dependencies]
yew = { git = "https://github.com/yewstack/yew.git", rev="8a16d4fc3d9b96a3aab7c98b3ab61b55deac9d3c" }
yewdux = {path = "../yewdux", version = "0.6"}
js-sys = "0.3.50"
gloo = "0.2.1"
web-sys = "0.3.55"
